server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8080/eureka/             #标识Server服务中心地址

#需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: client-one
